// Generated by gencpp from file path_sender/WayPoints.msg
// DO NOT EDIT!


#ifndef PATH_SENDER_MESSAGE_WAYPOINTS_H
#define PATH_SENDER_MESSAGE_WAYPOINTS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace path_sender
{
template <class ContainerAllocator>
struct WayPoints_
{
  typedef WayPoints_<ContainerAllocator> Type;

  WayPoints_()
    : points()  {
    }
  WayPoints_(const ContainerAllocator& _alloc)
    : points(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::path_sender::WayPoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path_sender::WayPoints_<ContainerAllocator> const> ConstPtr;

}; // struct WayPoints_

typedef ::path_sender::WayPoints_<std::allocator<void> > WayPoints;

typedef boost::shared_ptr< ::path_sender::WayPoints > WayPointsPtr;
typedef boost::shared_ptr< ::path_sender::WayPoints const> WayPointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path_sender::WayPoints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path_sender::WayPoints_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::path_sender::WayPoints_<ContainerAllocator1> & lhs, const ::path_sender::WayPoints_<ContainerAllocator2> & rhs)
{
  return lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::path_sender::WayPoints_<ContainerAllocator1> & lhs, const ::path_sender::WayPoints_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace path_sender

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::path_sender::WayPoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_sender::WayPoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_sender::WayPoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_sender::WayPoints_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_sender::WayPoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_sender::WayPoints_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path_sender::WayPoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3fb3f9dacc279b964c4c8341122c34df";
  }

  static const char* value(const ::path_sender::WayPoints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3fb3f9dacc279b96ULL;
  static const uint64_t static_value2 = 0x4c4c8341122c34dfULL;
};

template<class ContainerAllocator>
struct DataType< ::path_sender::WayPoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_sender/WayPoints";
  }

  static const char* value(const ::path_sender::WayPoints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path_sender::WayPoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point[] points\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::path_sender::WayPoints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path_sender::WayPoints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WayPoints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path_sender::WayPoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path_sender::WayPoints_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "points: ";
    if (v.points.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.points[i]);
    }
    if (v.points.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_SENDER_MESSAGE_WAYPOINTS_H
